nodeLinker: node-modules
npmAlwaysAuth: false
npmRegistryServer: "https://registry.npmjs.org"
npmRegistries:
  "https://gitlab.com/api/v4/packages/npm/":
    npmAlwaysAuth: true
    npmAuthToken: "${PAT_TOKEN}"

npmScopes:
  imapps:
    npmRegistryServer: "https://gitlab.com/api/v4/packages/npm/"