nodeLinker: node-modules
npmAlwaysAuth: false
npmRegistryServer: "https://registry.npmjs.org"

npmScopes:
  imapps:
    npmRegistryServer: "https://gitlab.com/api/v4/projects/61782506/packages/npm/"
    npmAlwaysAuth: true
    npmAuthToken: "${CI_JOB_TOKEN}"
