name: Build & Publish Docker

on:
  push:
    tags:
      - 'v*'

jobs:
  build-publish:
    uses: igor-siergiej/utils/.github/workflows/build-publish.yml@main
    with:
      services: '["api","web"]'
      is-monorepo: true
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
