name: Deploy 

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Write .env from Secrets
        run: |
          echo "VITE_API_URL=${{ secrets.VITE_API_URL }}" > .env
          echo "CONNECTION_URI=${{ secrets.CONNECTION_URI }}" >> .env
          echo "DATABASE_NAME=${{ secrets.DATABASE_NAME }}" >> .env
          echo "PORT=${{ secrets.PORT }}" >> .env

      - name: Build Docker images with Compose
        run: |
          docker compose build

      - name: Restart services with Compose
        run: |
          docker compose down
          docker compose up -d

