name: pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy app:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v1

      - name: yarn install workspace
        run: |
          yarn

      - name: build web 
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
        run: |
          yarn workspace web build 

      - name: deploy
        run: |
          cp -r packages/web/build/* /var/www/shoppingo.imapps.co.uk
      
      - name: build api
        run: | 
          yarn workspace api build
          yarn workspace api postBuild

      - name: deploy api
        run: |
          echo ${{ secrets.PASS }} | sudo -S cp -a packages/api/build/. /usr/local/bin/shoppingo-api-server
          echo ${{ secrets.PASS }} | sudo -S systemctl restart shoppingo-api-server.service
