name: Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  ci:
    uses: igor-siergiej/im-apps-utils/.github/workflows/ci.yml@main

  build-web:
    needs: ci
    uses: igor-siergiej/im-apps-utils/.github/workflows/docker-build.yml@main
    with:
      app_name: shoppingo-web
      registry: 192.168.68.54:31834
      dockerfile: packages/web/Dockerfile
      context_path: packages/web

  build-api:
    needs: ci
    uses: igor-siergiej/im-apps-utils/.github/workflows/docker-build.yml@main
    with:
      app_name: shoppingo-api
      registry: 192.168.68.54:31834
      dockerfile: packages/api/Dockerfile
      context_path: packages/api

  gitops-web:
    needs: build-web
    uses: igor-siergiej/im-apps-utils/.github/workflows/gitops-update.yml@main
    with:
      app_name: shoppingo-web
      registry: 192.168.68.54:31834
      version: ${{ needs.build-web.outputs.version }}
    secrets:
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}

  gitops-api:
    needs: build-api
    uses: igor-siergiej/im-apps-utils/.github/workflows/gitops-update.yml@main
    with:
      app_name: shoppingo-api
      registry: 192.168.68.54:31834
      version: ${{ needs.build-api.outputs.version }}
    secrets:
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}