name: Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  ci:
    uses: igor-siergiej/im-apps-utils/.github/workflows/ci.yml@main

  build-web:
    needs: ci
    uses: igor-siergiej/im-apps-utils/.github/workflows/docker-build.yml@main
    with:
      app_name: shoppingo-web
      registry: 192.168.68.54:31834
      dockerfile: packages/web/Dockerfile

  build-api:
    needs: ci
    uses: igor-siergiej/im-apps-utils/.github/workflows/docker-build.yml@main
    with:
      app_name: shoppingo-api
      registry: 192.168.68.54:31834
      dockerfile: packages/api/Dockerfile

  gitops:
    needs: [build-web, build-api]
    uses: igor-siergiej/im-apps-utils/.github/workflows/gitops-update.yml@main
    with:
      app_name: shoppingo
      registry: 192.168.68.54:31834
      version: ${{ needs.build-api.outputs.version }}
    secrets:
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}